append_info() do_patch()  do_delta() delta_upgrade() :  wrap up so that they create the /tmp dir, and clean up on return or  exception
DebDeltaError: define self.args